### ISSUE TITLE
Request for update

### ISSUE THREAD

**Issue by Sixdd6** [codetaylor/ct-mortar#1]
This is probably a long shot but any chance that this could be updated to 1.12/1/2 ? I'm working on a modpack and need literally exactly this functionality.

**Comment by codetaylor** [comment]
The project has been updated to work with 1.12.2.

The project has a new location on Curse: [https://minecraft.curseforge.com/projects/ct-mortar](https://minecraft.curseforge.com/projects/ct-mortar)
