### ISSUE TITLE
Integration with CraftTweaker/ZenScript

### ISSUE THREAD

**Issue by vico93** [codetaylor/ct-mortar#3]
Hi!

Does this mod have integration with [CraftTweaker](https://github.com/jaredlll08/CraftTweaker) to add mortar recipes?
It would be nice if it have.

Thanks in advance

**Comment by codetaylor** [comment]
No integration is necessary, just use CT's default recipe functionality.

For example, this makes a recipe to craft the wooden mortar with a wood plank to make dirt:

```
recipes.addShapeless(<minecraft:dirt> * 1, [<ctmortar:mortar_wood>.anyDamage(), <ore:plankWood>]);
```

Hope that helps! :)
